services:
  weaviate:
    container_name: weaviate
    image: cr.weaviate.io/semitechnologies/weaviate
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      AUTHENTICATION_OIDC_ENABLED: 'false'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - weaviate-network

  ingestion:
    image: tutless/ingestion:latest
    container_name: ingestion_gpu
    volumes:
      - /home/ai/payag/Batch_1/lawphil.net/:/source
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    depends_on:
      - weaviate
    networks:
      - weaviate-network
    

volumes:
  weaviate_data:
 
networks:
  weaviate-network:
    driver: bridge


     