services:
  ingestion:
    image: tutless/ingestion:latest
    container_name: ingestion_gpu
    volumes:
      - /home/ai/payag/payag_clean_tags/lawphil.net/:/source
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - payagbot

networks:
  payagbot:
    external: true
    name: payag_app_payagbot

