# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/payag.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/payag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/payag.proto\x12\x05payag\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\tChatQuery\x12\r\n\x05query\x18\x01 \x01(\t\"\x1e\n\x0c\x43hatResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2q\n\x0cPayagService\x12\x32\n\x08SayHello\x12\x13.payag.HelloRequest\x1a\x11.payag.HelloReply\x12-\n\x04\x43hat\x12\x10.payag.ChatQuery\x1a\x13.payag.ChatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.payag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=28
  _globals['_HELLOREQUEST']._serialized_end=56
  _globals['_HELLOREPLY']._serialized_start=58
  _globals['_HELLOREPLY']._serialized_end=87
  _globals['_CHATQUERY']._serialized_start=89
  _globals['_CHATQUERY']._serialized_end=115
  _globals['_CHATRESPONSE']._serialized_start=117
  _globals['_CHATRESPONSE']._serialized_end=147
  _globals['_PAYAGSERVICE']._serialized_start=149
  _globals['_PAYAGSERVICE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
