services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      AUTHENTICATION_OIDC_ENABLED: 'true'
      AUTHENTICATION_OIDC_ISSUER: 'http://keycloak:8080/realms/payag-weaviate'
      AUTHENTICATION_OIDC_CLIENT_ID: payag-weaviate-client
      AUTHENTICATION_OIDC_USERNAME_CLAIM: 'preferred_username'
      LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu
    

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    deploy:
      replicas: 1
    command: start-dev
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin  
volumes:
  weaviate_data:
  keycloak_data:

     